### PR TITLE
Feature: Video support

### PR DESCRIPTION
**Pull request by azachar**
Hello!

Thank you for your nice library. I have added the video support, so images now can contain also video.

In the future release it would be better to call the image field better, such as medium. Because now it represent an image or a video.

Cheers,
Andrej

### CODE REVIEW

**Comment by azachar** [comment]
Also I have provided the fullscreen support, so all images are nicely spread within provided limits of min and max possible size.

**Comment by compact** [comment]
Thanks! The fullscreen scaling should be optional, and the video dimensions/aspect ratio should be configurable. I'll have time to edit this next week if you don't.

**Comment by azachar** [comment]
That would be great if you can provide it!

**Comment by compact** [comment]
Updated:

http://compact.github.io/angular-bootstrap-lightbox/demo4/index.html
http://compact.github.io/angular-bootstrap-lightbox/demo5/index.html

**Pull request merged**
